### ISSUE TITLE
Design | Hero dimensions are not accurate to the design

### ISSUE THREAD

**Issue by EstebanBorai** [rust-lang-ar/rust-lang-ar.github.io#16]
## Current

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34756077/134107331-52d1ce03-9892-41bf-a72e-5b9623d065e0.png">

### Notes

- [x] Hero's main text is larger than the one shown in the design for the same scale
- [x] Hero's main text must be in semi-bold instead of regular
- [x] Hero's brief text must be in black instead of gray
- [x] There's missing space between the Hero's main text and the text below

## Expected

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/34756077/134107364-1b10d0d7-37ef-4640-8c66-7959a56db99f.png">

https://xd.adobe.com/view/a6e8590a-79fc-48f7-b07d-03411c8df981-f3bb/screen/4ca7f176-c725-49c1-ac81-93e99adaea90

**Comment by Phosphorus-M** [comment]
In point 2, Hero's main text is not semi-bold in the mock it's in bold. 
And besides, the scale is in 1920px like in the mockup if you want see how the page look changes the resolution.

The font size in the mock is not responsive, is important to understand that the design is not prepared for mobile.
If I use the exact font size in the mock it's possible that I break the design but even so I did a changes
